name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
      - v[0-9]+.*-pre

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-pre') }}

  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Install musl-tools (for musl targets)
        if: contains(matrix.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      
      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: mdbook-betterlink
          target: ${{ matrix.target }}
          archive: mdbook-betterlink-${{ github.ref_name }}-${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tar: ${{ !contains(matrix.target, 'windows') }}
          zip: ${{ contains(matrix.target, 'windows') }}
